/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type BuildingReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "building";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Unit = {
  _id: string;
  _type: "unit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  code?: string;
  building?: BuildingReference;
  floor?: number;
  unitType?: "banesor" | "afarist";
  rooms?: number;
  areaNet?: number;
  areaGross?: number;
  orientation?: Array<string>;
  status?: "i_lire" | "i_rezervuar" | "i_shitur";
  svgPath?: string;
  floorPlanImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Building = {
  _id: string;
  _type: "building";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  project?: ProjectReference;
  facadeImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  facadeViewBox?: string;
  floorsCount?: number;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroButtonText?: string;
  heroButtonLink?: string;
  yearsOfExperience?: number;
  finishedProjects?: number;
  apartmentsDelivered?: number;
  aboutTitle?: string;
  aboutText?: string;
  aboutImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  phone?: string;
  whatsapp?: string;
  email?: string;
  address?: string;
  socialLinks?: {
    instagram?: string;
    facebook?: string;
    linkedin?: string;
  };
  defaultShareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  city?: string;
  status?: "construction" | "finished" | "coming-soon";
  mainPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: string;
  description?: string;
  specifications?: Array<string>;
  amenities?: Array<string>;
  location?: Geopoint;
  brochure?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  finishDate?: string;
  featured?: boolean;
  paymentPlan?: Array<{
    label?: string;
    percentage?: number;
    _key: string;
  }>;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | BuildingReference
  | SanityImageAssetReference
  | Unit
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectReference
  | Building
  | Slug
  | HomePage
  | SiteSettings
  | Page
  | SanityFileAssetReference
  | Project
  | Geopoint
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: sanity/lib/queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "project"] | order(title asc) {    id,    _createdAt,    title,    slug,    city,    status,    mainPhoto {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    description,    featured  }
export type AllProjectsQueryResult = Array<{
  id: null;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  city: string | null;
  status: "coming-soon" | "construction" | "finished" | null;
  mainPhoto: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  featured: boolean | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    title,    slug,    city,    status,    mainPhoto {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    video,    description,    specifications,    amenities,    paymentPlan,    location,    brochure {  asset->{    _id,    url,    originalFilename,    mimeType  }},    gallery[] {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    finishDate,    featured  }
export type ProjectBySlugQueryResult = {
  title: string | null;
  slug: Slug | null;
  city: string | null;
  status: "coming-soon" | "construction" | "finished" | null;
  mainPhoto: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  video: string | null;
  description: string | null;
  specifications: Array<string> | null;
  amenities: Array<string> | null;
  paymentPlan: Array<{
    label?: string;
    percentage?: number;
    _key: string;
  }> | null;
  location: Geopoint | null;
  brochure: {
    asset: {
      _id: string;
      url: string | null;
      originalFilename: string | null;
      mimeType: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  finishDate: string | null;
  featured: boolean | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    phone,    whatsapp,    email,    address,    socialLinks,    defaultShareImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }}  }
export type SiteSettingsQueryResult = {
  phone: string | null;
  whatsapp: string | null;
  email: string | null;
  address: string | null;
  socialLinks: {
    instagram?: string;
    facebook?: string;
    linkedin?: string;
  } | null;
  defaultShareImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: *[    _type == "page" &&    slug.current == $slug &&    language == $language  ][0] {    title,    slug,    body,    seoTitle,    seoDescription,    seoImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }}  }
export type PageBySlugQueryResult = {
  title: string | null;
  slug: Slug | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0] {    heroTitle,    heroImage {      ...,      asset->{  _id,  url,  metadata {    lqip,    dimensions {      width,      height,      aspectRatio    }  }}    },    heroButtonText,    heroButtonLink,    yearsOfExperience,    finishedProjects,    apartmentsDelivered,    aboutTitle,    aboutText,    afarizmiIntro,    aboutImage {      ...,      asset->{  _id,  url,  metadata {    lqip,    dimensions {      width,      height,      aspectRatio    }  }}    }  }
export type HomePageQueryResult = {
  heroTitle: string | null;
  heroImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  heroButtonText: string | null;
  heroButtonLink: string | null;
  yearsOfExperience: number | null;
  finishedProjects: number | null;
  apartmentsDelivered: number | null;
  aboutTitle: string | null;
  aboutText: string | null;
  afarizmiIntro: null;
  aboutImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allBuildingsQuery
// Query: *[_type == "building"] | order(order asc) {  _id,  title,  "slug": slug.current,  facadeImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},  "total": count(*[_type == "unit" && building._ref == ^._id]),  "free": count(*[_type == "unit" && building._ref == ^._id && status == "i_lire"])}
export type AllBuildingsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  facadeImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  total: number;
  free: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: buildingBySlugQuery
// Query: *[_type == "building" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    order,    facadeImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    facadeViewBox,    floorsCount  }
export type BuildingBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  order: number | null;
  facadeImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  facadeViewBox: string | null;
  floorsCount: number | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: unitsByBuildingQuery
// Query: *[_type == "unit" && building._ref == $buildingId] {    _id,    code,    floor,    unitType,    rooms,    areaNet,    areaGross,    orientation,    status,    svgPath,    floorPlanImage,    price  }
export type UnitsByBuildingQueryResult = Array<{
  _id: string;
  code: string | null;
  floor: number | null;
  unitType: "afarist" | "banesor" | null;
  rooms: number | null;
  areaNet: number | null;
  areaGross: number | null;
  orientation: Array<string> | null;
  status: "i_lire" | "i_rezervuar" | "i_shitur" | null;
  svgPath: string | null;
  floorPlanImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  price: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(title asc) {\n    id,\n    _createdAt,\n    title,\n    slug,\n    city,\n    status,\n    mainPhoto {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    description,\n    featured\n  }\n': AllProjectsQueryResult;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    title,\n    slug,\n    city,\n    status,\n    mainPhoto {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    video,\n    description,\n    specifications,\n    amenities,\n    paymentPlan,\n    location,\n    brochure {\n  asset->{\n    _id,\n    url,\n    originalFilename,\n    mimeType\n  }\n},\n    gallery[] {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    finishDate,\n    featured\n  }\n': ProjectBySlugQueryResult;
    '\n  *[_type == "siteSettings"][0] {\n    phone,\n    whatsapp,\n    email,\n    address,\n    socialLinks,\n    defaultShareImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n  }\n': SiteSettingsQueryResult;
    '\n *[\n    _type == "page" &&\n    slug.current == $slug &&\n    language == $language\n  ][0] {\n    title,\n    slug,\n    body,\n    seoTitle,\n    seoDescription,\n    seoImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n  }\n': PageBySlugQueryResult;
    '\n  *[_type == "homePage"][0] {\n    heroTitle,\n    heroImage {\n      ...,\n      asset->{\n  _id,\n  url,\n  metadata {\n    lqip,\n    dimensions {\n      width,\n      height,\n      aspectRatio\n    }\n  }\n}\n    },\n    heroButtonText,\n    heroButtonLink,\n    yearsOfExperience,\n    finishedProjects,\n    apartmentsDelivered,\n    aboutTitle,\n    aboutText,\n    afarizmiIntro,\n    aboutImage {\n      ...,\n      asset->{\n  _id,\n  url,\n  metadata {\n    lqip,\n    dimensions {\n      width,\n      height,\n      aspectRatio\n    }\n  }\n}\n    }\n  }\n': HomePageQueryResult;
    '*[_type == "building"] | order(order asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  facadeImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n  "total": count(*[_type == "unit" && building._ref == ^._id]),\n  "free": count(*[_type == "unit" && building._ref == ^._id && status == "i_lire"])\n}': AllBuildingsQueryResult;
    '\n  *[_type == "building" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    order,\n    facadeImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    facadeViewBox,\n    floorsCount\n  }\n': BuildingBySlugQueryResult;
    '\n  *[_type == "unit" && building._ref == $buildingId] {\n    _id,\n    code,\n    floor,\n    unitType,\n    rooms,\n    areaNet,\n    areaGross,\n    orientation,\n    status,\n    svgPath,\n    floorPlanImage,\n    price\n  }\n': UnitsByBuildingQueryResult;
  }
}
