/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type BuildingReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "building";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Unit = {
  _id: string;
  _type: "unit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  code?: string;
  building?: BuildingReference;
  floor?: number;
  unitType?: "banesor" | "afarist";
  rooms?: number;
  areaNet?: number;
  areaGross?: number;
  orientation?: Array<string>;
  status?: "i_lire" | "i_rezervuar" | "i_shitur";
  svgPath?: string;
  floorPlanImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  floorPlanPdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  price?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Building = {
  _id: string;
  _type: "building";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: Slug;
  project?: ProjectReference;
  facadeImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  facadeViewBox?: string;
  floorsCount?: number;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type LocaleString = {
  _type: "localeString";
  sq?: string;
  en?: string;
  de?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: LocaleString;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroButtonText?: LocaleString;
  heroButtonLink?: string;
  yearsOfExperience?: number;
  finishedProjects?: number;
  apartmentsDelivered?: number;
  aboutTitle?: LocaleString;
  aboutText?: LocaleText;
  aboutImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  afarizmiIntro?: LocaleText;
};

export type LocaleText = {
  _type: "localeText";
  sq?: string;
  en?: string;
  de?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  phone?: string;
  whatsapp?: string;
  email?: string;
  address?: string;
  socialLinks?: {
    instagram?: string;
    facebook?: string;
    linkedin?: string;
  };
  defaultShareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: Slug;
  body?: LocaleBlock;
  seoTitle?: LocaleString;
  seoDescription?: LocaleText;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LocaleBlock = {
  _type: "localeBlock";
  sq?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  de?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: Slug;
  city?: LocaleString;
  status?: "construction" | "finished" | "coming-soon";
  mainPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: string;
  description?: LocaleText;
  specifications?: Array<
    {
      _key: string;
    } & LocaleString
  >;
  amenities?: Array<
    {
      _key: string;
    } & LocaleString
  >;
  location?: Geopoint;
  brochure?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  finishDate?: string;
  featured?: boolean;
  paymentPlan?: Array<{
    label?: LocaleString;
    percentage?: number;
    _key: string;
  }>;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | BuildingReference
  | SanityImageAssetReference
  | SanityFileAssetReference
  | Unit
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectReference
  | Building
  | Slug
  | LocaleString
  | HomePage
  | LocaleText
  | SiteSettings
  | Page
  | LocaleBlock
  | Project
  | Geopoint
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: sanity/lib/queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "project"] | order(select(    $locale == "en" => coalesce(title.en, title.sq),    $locale == "de" => coalesce(title.de, title.sq),    title.sq  ) asc) {    id,    _createdAt,    "title": select(    $locale == "en" => coalesce(title.en, title.sq),    $locale == "de" => coalesce(title.de, title.sq),    title.sq  ),    slug,    "city": select(    $locale == "en" => coalesce(city.en, city.sq),    $locale == "de" => coalesce(city.de, city.sq),    city.sq  ),    "cityKey": coalesce(city.sq, city.en, city.de),    status,    mainPhoto {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    "description": select(    $locale == "en" => coalesce(description.en, description.sq),    $locale == "de" => coalesce(description.de, description.sq),    description.sq  ),    featured  }
export type AllProjectsQueryResult = Array<{
  id: null;
  _createdAt: string;
  title: string | null;
  slug: Slug | null;
  city: string | null;
  cityKey: string | null;
  status: "coming-soon" | "construction" | "finished" | null;
  mainPhoto: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  featured: boolean | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    "title": select(    $locale == "en" => coalesce(title.en, title.sq),    $locale == "de" => coalesce(title.de, title.sq),    title.sq  ),    slug,    "city": select(    $locale == "en" => coalesce(city.en, city.sq),    $locale == "de" => coalesce(city.de, city.sq),    city.sq  ),    "cityKey": coalesce(city.sq, city.en, city.de),    status,    mainPhoto {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    video,    "description": select(    $locale == "en" => coalesce(description.en, description.sq),    $locale == "de" => coalesce(description.de, description.sq),    description.sq  ),    "specifications": specifications[]{    "v": select(      $locale == "en" => coalesce(@.en, @.sq),      $locale == "de" => coalesce(@.de, @.sq),      @.sq    )  }.v,    "amenities": amenities[]{    "v": select(      $locale == "en" => coalesce(@.en, @.sq),      $locale == "de" => coalesce(@.de, @.sq),      @.sq    )  }.v,    paymentPlan[] {      percentage,      "label": select(    $locale == "en" => coalesce(label.en, label.sq),    $locale == "de" => coalesce(label.de, label.sq),    label.sq  )    },    location,    brochure {  asset->{    _id,    url,    originalFilename,    mimeType  }},    gallery[] {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    finishDate,    featured  }
export type ProjectBySlugQueryResult = {
  title: string | null;
  slug: Slug | null;
  city: string | null;
  cityKey: string | null;
  status: "coming-soon" | "construction" | "finished" | null;
  mainPhoto: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  video: string | null;
  description: string | null;
  specifications: Array<string | null> | null;
  amenities: Array<string | null> | null;
  paymentPlan: Array<{
    percentage: number | null;
    label: string | null;
  }> | null;
  location: Geopoint | null;
  brochure: {
    asset: {
      _id: string;
      url: string | null;
      originalFilename: string | null;
      mimeType: string | null;
    } | null;
  } | null;
  gallery: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  finishDate: string | null;
  featured: boolean | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    phone,    whatsapp,    email,    address,    socialLinks,    defaultShareImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }}  }
export type SiteSettingsQueryResult = {
  phone: string | null;
  whatsapp: string | null;
  email: string | null;
  address: string | null;
  socialLinks: {
    instagram?: string;
    facebook?: string;
    linkedin?: string;
  } | null;
  defaultShareImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: *[    _type == "page" &&    slug.current == $slug  ][0] {    "title": select(    $locale == "en" => coalesce(title.en, title.sq),    $locale == "de" => coalesce(title.de, title.sq),    title.sq  ),    slug,    "body": select(    $locale == "en" => coalesce(body.en, body.sq),    $locale == "de" => coalesce(body.de, body.sq),    body.sq  ),    "seoTitle": select(    $locale == "en" => coalesce(seoTitle.en, seoTitle.sq),    $locale == "de" => coalesce(seoTitle.de, seoTitle.sq),    seoTitle.sq  ),    "seoDescription": select(    $locale == "en" => coalesce(seoDescription.en, seoDescription.sq),    $locale == "de" => coalesce(seoDescription.de, seoDescription.sq),    seoDescription.sq  ),    seoImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }}  }
export type PageBySlugQueryResult = {
  title: string | null;
  slug: Slug | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  seoImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0] {    "heroTitle": select(    $locale == "en" => coalesce(heroTitle.en, heroTitle.sq),    $locale == "de" => coalesce(heroTitle.de, heroTitle.sq),    heroTitle.sq  ),    heroImage {      ...,      asset->{  _id,  url,  metadata {    lqip,    dimensions {      width,      height,      aspectRatio    }  }}    },    "heroButtonText": select(    $locale == "en" => coalesce(heroButtonText.en, heroButtonText.sq),    $locale == "de" => coalesce(heroButtonText.de, heroButtonText.sq),    heroButtonText.sq  ),    heroButtonLink,    yearsOfExperience,    finishedProjects,    apartmentsDelivered,    "aboutTitle": select(    $locale == "en" => coalesce(aboutTitle.en, aboutTitle.sq),    $locale == "de" => coalesce(aboutTitle.de, aboutTitle.sq),    aboutTitle.sq  ),    "aboutText": select(    $locale == "en" => coalesce(aboutText.en, aboutText.sq),    $locale == "de" => coalesce(aboutText.de, aboutText.sq),    aboutText.sq  ),    "afarizmiIntro": select(    $locale == "en" => coalesce(afarizmiIntro.en, afarizmiIntro.sq),    $locale == "de" => coalesce(afarizmiIntro.de, afarizmiIntro.sq),    afarizmiIntro.sq  ),    aboutImage {      ...,      asset->{  _id,  url,  metadata {    lqip,    dimensions {      width,      height,      aspectRatio    }  }}    }  }
export type HomePageQueryResult = {
  heroTitle: string | null;
  heroImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  heroButtonText: string | null;
  heroButtonLink: string | null;
  yearsOfExperience: number | null;
  finishedProjects: number | null;
  apartmentsDelivered: number | null;
  aboutTitle: string | null;
  aboutText: string | null;
  afarizmiIntro: string | null;
  aboutImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allBuildingsQuery
// Query: *[_type == "building"] | order(order asc) {  _id,  "title": select(    $locale == "en" => coalesce(title.en, title.sq),    $locale == "de" => coalesce(title.de, title.sq),    title.sq  ),  "slug": slug.current,  facadeImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},  "total": count(*[_type == "unit" && building._ref == ^._id]),  "free": count(*[_type == "unit" && building._ref == ^._id && status == "i_lire"])}
export type AllBuildingsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  facadeImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  total: number;
  free: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: buildingBySlugQuery
// Query: *[_type == "building" && slug.current == $slug][0] {    _id,    "title": select(    $locale == "en" => coalesce(title.en, title.sq),    $locale == "de" => coalesce(title.de, title.sq),    title.sq  ),    "slug": slug.current,    order,    facadeImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    facadeViewBox,    floorsCount  }
export type BuildingBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  order: number | null;
  facadeImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  facadeViewBox: string | null;
  floorsCount: number | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: unitsByBuildingQuery
// Query: *[_type == "unit" && building._ref == $buildingId] {    _id,    code,    floor,    unitType,    rooms,    areaNet,    areaGross,    orientation,    status,    svgPath,    floorPlanImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    floorPlanPdf {  asset->{    _id,    url,    originalFilename,    mimeType  }},    price  }
export type UnitsByBuildingQueryResult = Array<{
  _id: string;
  code: string | null;
  floor: number | null;
  unitType: "afarist" | "banesor" | null;
  rooms: number | null;
  areaNet: number | null;
  areaGross: number | null;
  orientation: Array<string> | null;
  status: "i_lire" | "i_rezervuar" | "i_shitur" | null;
  svgPath: string | null;
  floorPlanImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  floorPlanPdf: {
    asset: {
      _id: string;
      url: string | null;
      originalFilename: string | null;
      mimeType: string | null;
    } | null;
  } | null;
  price: number | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: unitByBuildingAndCodeQuery
// Query: *[    _type == "unit" &&    building->slug.current == $buildingSlug &&    code == $unitCode  ][0] {    _id,    code,    floor,    unitType,    rooms,    areaNet,    areaGross,    orientation,    status,    svgPath,    floorPlanImage {  ...,  asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  }},    floorPlanPdf {      asset->{        _id,        url,        originalFilename,        mimeType      }    },    price,    "building": building->{      _id,      "title": select(    $locale == "en" => coalesce(title.en, title.sq),    $locale == "de" => coalesce(title.de, title.sq),    title.sq  ),      "slug": slug.current,      floorsCount    }  }
export type UnitByBuildingAndCodeQueryResult = {
  _id: string;
  code: string | null;
  floor: number | null;
  unitType: "afarist" | "banesor" | null;
  rooms: number | null;
  areaNet: number | null;
  areaGross: number | null;
  orientation: Array<string> | null;
  status: "i_lire" | "i_rezervuar" | "i_shitur" | null;
  svgPath: string | null;
  floorPlanImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  floorPlanPdf: {
    asset: {
      _id: string;
      url: string | null;
      originalFilename: string | null;
      mimeType: string | null;
    } | null;
  } | null;
  price: number | null;
  building: {
    _id: string;
    title: string | null;
    slug: string | null;
    floorsCount: number | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: allUnitsQuery
// Query: *[_type == "unit"] {    _id,    code,    "buildingSlug": building->slug.current  }
export type AllUnitsQueryResult = Array<{
  _id: string;
  code: string | null;
  buildingSlug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(select(\n    $locale == "en" => coalesce(title.en, title.sq),\n    $locale == "de" => coalesce(title.de, title.sq),\n    title.sq\n  ) asc) {\n    id,\n    _createdAt,\n    "title": select(\n    $locale == "en" => coalesce(title.en, title.sq),\n    $locale == "de" => coalesce(title.de, title.sq),\n    title.sq\n  ),\n    slug,\n    "city": select(\n    $locale == "en" => coalesce(city.en, city.sq),\n    $locale == "de" => coalesce(city.de, city.sq),\n    city.sq\n  ),\n    "cityKey": coalesce(city.sq, city.en, city.de),\n    status,\n    mainPhoto {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    "description": select(\n    $locale == "en" => coalesce(description.en, description.sq),\n    $locale == "de" => coalesce(description.de, description.sq),\n    description.sq\n  ),\n    featured\n  }\n': AllProjectsQueryResult;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    "title": select(\n    $locale == "en" => coalesce(title.en, title.sq),\n    $locale == "de" => coalesce(title.de, title.sq),\n    title.sq\n  ),\n    slug,\n    "city": select(\n    $locale == "en" => coalesce(city.en, city.sq),\n    $locale == "de" => coalesce(city.de, city.sq),\n    city.sq\n  ),\n    "cityKey": coalesce(city.sq, city.en, city.de),\n    status,\n    mainPhoto {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    video,\n    "description": select(\n    $locale == "en" => coalesce(description.en, description.sq),\n    $locale == "de" => coalesce(description.de, description.sq),\n    description.sq\n  ),\n    "specifications": specifications[]{\n    "v": select(\n      $locale == "en" => coalesce(@.en, @.sq),\n      $locale == "de" => coalesce(@.de, @.sq),\n      @.sq\n    )\n  }.v,\n    "amenities": amenities[]{\n    "v": select(\n      $locale == "en" => coalesce(@.en, @.sq),\n      $locale == "de" => coalesce(@.de, @.sq),\n      @.sq\n    )\n  }.v,\n    paymentPlan[] {\n      percentage,\n      "label": select(\n    $locale == "en" => coalesce(label.en, label.sq),\n    $locale == "de" => coalesce(label.de, label.sq),\n    label.sq\n  )\n    },\n    location,\n    brochure {\n  asset->{\n    _id,\n    url,\n    originalFilename,\n    mimeType\n  }\n},\n    gallery[] {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    finishDate,\n    featured\n  }\n': ProjectBySlugQueryResult;
    '\n  *[_type == "siteSettings"][0] {\n    phone,\n    whatsapp,\n    email,\n    address,\n    socialLinks,\n    defaultShareImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n  }\n': SiteSettingsQueryResult;
    '\n *[\n    _type == "page" &&\n    slug.current == $slug\n  ][0] {\n    "title": select(\n    $locale == "en" => coalesce(title.en, title.sq),\n    $locale == "de" => coalesce(title.de, title.sq),\n    title.sq\n  ),\n    slug,\n    "body": select(\n    $locale == "en" => coalesce(body.en, body.sq),\n    $locale == "de" => coalesce(body.de, body.sq),\n    body.sq\n  ),\n    "seoTitle": select(\n    $locale == "en" => coalesce(seoTitle.en, seoTitle.sq),\n    $locale == "de" => coalesce(seoTitle.de, seoTitle.sq),\n    seoTitle.sq\n  ),\n    "seoDescription": select(\n    $locale == "en" => coalesce(seoDescription.en, seoDescription.sq),\n    $locale == "de" => coalesce(seoDescription.de, seoDescription.sq),\n    seoDescription.sq\n  ),\n    seoImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n}\n  }\n': PageBySlugQueryResult;
    '\n  *[_type == "homePage"][0] {\n    "heroTitle": select(\n    $locale == "en" => coalesce(heroTitle.en, heroTitle.sq),\n    $locale == "de" => coalesce(heroTitle.de, heroTitle.sq),\n    heroTitle.sq\n  ),\n    heroImage {\n      ...,\n      asset->{\n  _id,\n  url,\n  metadata {\n    lqip,\n    dimensions {\n      width,\n      height,\n      aspectRatio\n    }\n  }\n}\n    },\n    "heroButtonText": select(\n    $locale == "en" => coalesce(heroButtonText.en, heroButtonText.sq),\n    $locale == "de" => coalesce(heroButtonText.de, heroButtonText.sq),\n    heroButtonText.sq\n  ),\n    heroButtonLink,\n    yearsOfExperience,\n    finishedProjects,\n    apartmentsDelivered,\n    "aboutTitle": select(\n    $locale == "en" => coalesce(aboutTitle.en, aboutTitle.sq),\n    $locale == "de" => coalesce(aboutTitle.de, aboutTitle.sq),\n    aboutTitle.sq\n  ),\n    "aboutText": select(\n    $locale == "en" => coalesce(aboutText.en, aboutText.sq),\n    $locale == "de" => coalesce(aboutText.de, aboutText.sq),\n    aboutText.sq\n  ),\n    "afarizmiIntro": select(\n    $locale == "en" => coalesce(afarizmiIntro.en, afarizmiIntro.sq),\n    $locale == "de" => coalesce(afarizmiIntro.de, afarizmiIntro.sq),\n    afarizmiIntro.sq\n  ),\n    aboutImage {\n      ...,\n      asset->{\n  _id,\n  url,\n  metadata {\n    lqip,\n    dimensions {\n      width,\n      height,\n      aspectRatio\n    }\n  }\n}\n    }\n  }\n': HomePageQueryResult;
    '*[_type == "building"] | order(order asc) {\n  _id,\n  "title": select(\n    $locale == "en" => coalesce(title.en, title.sq),\n    $locale == "de" => coalesce(title.de, title.sq),\n    title.sq\n  ),\n  "slug": slug.current,\n  facadeImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n  "total": count(*[_type == "unit" && building._ref == ^._id]),\n  "free": count(*[_type == "unit" && building._ref == ^._id && status == "i_lire"])\n}': AllBuildingsQueryResult;
    '\n  *[_type == "building" && slug.current == $slug][0] {\n    _id,\n    "title": select(\n    $locale == "en" => coalesce(title.en, title.sq),\n    $locale == "de" => coalesce(title.de, title.sq),\n    title.sq\n  ),\n    "slug": slug.current,\n    order,\n    facadeImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    facadeViewBox,\n    floorsCount\n  }\n': BuildingBySlugQueryResult;
    '\n  *[_type == "unit" && building._ref == $buildingId] {\n    _id,\n    code,\n    floor,\n    unitType,\n    rooms,\n    areaNet,\n    areaGross,\n    orientation,\n    status,\n    svgPath,\n    floorPlanImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    floorPlanPdf {\n  asset->{\n    _id,\n    url,\n    originalFilename,\n    mimeType\n  }\n},\n    price\n  }\n': UnitsByBuildingQueryResult;
    '\n  *[\n    _type == "unit" &&\n    building->slug.current == $buildingSlug &&\n    code == $unitCode\n  ][0] {\n    _id,\n    code,\n    floor,\n    unitType,\n    rooms,\n    areaNet,\n    areaGross,\n    orientation,\n    status,\n    svgPath,\n    floorPlanImage {\n  ...,\n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  }\n},\n    floorPlanPdf {\n      asset->{\n        _id,\n        url,\n        originalFilename,\n        mimeType\n      }\n    },\n    price,\n    "building": building->{\n      _id,\n      "title": select(\n    $locale == "en" => coalesce(title.en, title.sq),\n    $locale == "de" => coalesce(title.de, title.sq),\n    title.sq\n  ),\n      "slug": slug.current,\n      floorsCount\n    }\n  }\n': UnitByBuildingAndCodeQueryResult;
    '\n  *[_type == "unit"] {\n    _id,\n    code,\n    "buildingSlug": building->slug.current\n  }\n': AllUnitsQueryResult;
  }
}
